[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
version = {attr = "clitheme._version.__version__"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["clitheme", "clitheme.*"]

[tool.setuptools.package-data]
"*" = ["*"]

[project]
name = "clitheme"
dynamic = ["version"]
authors = [
  { name="swiftycode", email="3291929745@qq.com" },
]
description = "A text theming library for command line applications"
readme = ".github/README.md"
license = {text = "GNU General Public License v3 (GPLv3)"}
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
    "Private :: Do Not Upload"
]

[project.scripts]
clitheme = "clitheme:cli._script_main"
clitheme-exec = "clitheme:exec._script_main"
clitheme-man = "clitheme:man._script_main"

[project.urls]
Repository = "https://gitee.com/swiftycode/clitheme"
Documentation = "https://gitee.com/swiftycode/clitheme/wikis/pages"
Issues = "https://gitee.com/swiftycode/clitheme/issues"