[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
version = {attr = "clitheme._version.__version__"}

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["*test*"]

[tool.setuptools.package-data]
"*" = ["*"]

[project]
name = "clitheme"
dynamic = ["version"]
authors = [
  { name="swiftycode", email="3291929745@qq.com" },
]
description = "A text theming library for command line applications"
readme = "README.en.md"
license = {file = "LICENSE"}
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]

[project.scripts]
clitheme = "clitheme:cli.script_main"
clitheme-exec= "clitheme:exec.script_main"

[project.urls]
Repository = "https://gitee.com/swiftycode/clitheme"
Documentation = "https://gitee.com/swiftycode/clitheme/wikis/pages"
Issues = "https://gitee.com/swiftycode/clitheme/issues"