.TH clitheme 1 2024-12-17
.SH NAME 
clitheme \- frontend to customize output of applications
.SH SYNOPSIS 
.B clitheme [COMMAND] [OPTIONS]
.SH DESCRIPTION 
\fIclitheme\fR is a framework for applications that allows users to customize its output and messages through theme definition files. This CLI interface allows the user to control their current settings and theme definition on the system. 
.SH OPTIONS
.TP
.B apply-theme [themedef-file(s)] [--overlay] [--preserve-temp]
Applies the given theme definition file(s) into the current system. Supported applications will immediately start using the defined values after performing this operation.

Specify \fB--overlay\fR to append value definitions in the file(s) onto the current data.

Specify \fB--preserve-temp\fR to prevent the temporary directory from removed after the operation.
.TP 
.B get-current-theme-info [--name] [--file-path]
Outputs detailed information about the currently applied theme. If multiple themes are applied using the \fB--overlay\fR option, outputs detailed information for each applied theme.

Specify \fB--name\fR to only display the name of each theme.

Specify \fB--file-path\fR to only display the source file path of each theme.

(Both will be displayed when both specified)

.TP
.B unset-current-theme
Removes the current theme data from the system. Supported applications will immediately stop using the defined values after this operation.
.TP
.B update-theme
Re-applies the theme definition files specified in the previous "apply-theme" command (previous commands if \fB--overlay\fR is used)

Calling this command is equivalent to calling "clitheme apply-theme" with previously-specified files.
.TP
.B generate-data [themedef-file(s)] [--overlay]
Generates the data hierarchy for the given theme definition file(s). This operation generates the same data as \fBapply-theme\fR, but does not apply it onto the system. 

This command is for debug purposes only.
.TP
.B --help
Outputs a short help message consisting of available commands.
.TP
.B --version
Outputs the current version of the program.
.SH SEE ALSO
\fIclitheme-exec(1)\fR, \fIclitheme-man(1)\fR

For more information, please see the project homepage and the project wiki:
.P
.I https://gitee.com/swiftycode/clitheme
.P
.I https://gitee.com/swiftycode/clitheme/wikis/pages
or
.I https://gitee.com/swiftycode/clitheme-wiki-repo