.TH clitheme-man 1 2024-05-07
.SH NAME
clitheme\-man \- access manual pages in the current theme
.SH SYNOPSIS
.B clitheme-man [OPTIONS]
.SH DESCRIPTION
\fIclitheme-man\fR is a wrapper for \fIman(1)\fR that accesses the manual pages defined in a theme definition file. The current theme definition on the system is controlled through \fIclitheme(1)\fR.
.P
\fIclitheme-man\fR is designed to be used the same way as \fIman(1)\fR; the same arguments and options will work on \fIclitheme-man\fR.
.SH OPTIONS
For a list of options you can use, please see \fIman(1)\fR.
.SH SEE ALSO
\fIclitheme(1)\fR, \fIman(1)\fR